[package]
name = "mic-mute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10"
anyhow = "1.0.69" # error handling
tao = "0.18" # window manager and event loop
tray-icon = "0.4" # system tray
image = "0.24" # icon image manipulation
global-hotkey = "0.1"
async-std = "1.12"
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
objc = "0.2"
dark-light = "1.0" # detect appearance mode
coreaudio-rs = "0.11" # macos audio
core-foundation-sys = "0.8"
