---
version: "3"

vars:
  PROJECT_DIR:
    sh: git rev-parse --show-toplevel

env:
  ROOT_DIR: "{{.PROJECT_DIR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  init:
    desc: Install dependencies
    cmds:
      - task: dependencies

  dependencies:
    internal: true
    desc: Project dependencies
    cmds:
        - cargo install cargo-watch
    status:
      - test -f $HOME/.cargo/bin/cargo-watch

  dependencies-release:
    internal: true
    desc: Release dependencies
    cmds:
      - cargo install cargo-bundle
    status:
      - test -f $HOME/.cargo/bin/cargo-bundle

  start:
    desc: Compile, run and watch for changes
    aliases:
      - watch
    cmds:
      - cargo watch -x run
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  debug:
    cmds:
      - ./target/debug/mvcm
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  lint:
    cmds:
      - cargo clippy --locked --release -- -D warnings
      - cargo fmt -- --check

  test:
    cmds:
      - cargo test

  build:
    cmds:
      - cargo build

  release:
    cmds:
      - task: dependencies-release
      - task: release-arch
        vars:
          TARGET: aarch64-apple-darwin
    env:
      RUST_LOG: warn

  release-arch:
    internal: true
    cmds:
      - cargo build --locked --release --target {{ .TARGET }}
      - cargo bundle --release --target {{ .TARGET }}
      - TARGET={{ .TARGET }} cargo run --bin post-build
      - open ./target/{{ .TARGET }}/release/bundle/osx
    env:
      RUST_LOG: warn


  clean:
    cmds:
      - rm -rf ./target
