---
version: "3"

vars:
  PROJECT_DIR:
    sh: git rev-parse --show-toplevel

env:
  ROOT_DIR: "{{.PROJECT_DIR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  init:
    desc: Install dependencies and setup environment
    cmds:
      - task: dependencies

  dependencies:
    desc: Setup project dependencies
    cmds:
        - cargo install cargo-watch

  start:
    aliases:
      - watch
    cmds:
      - cargo watch -x run
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  debug:
    cmds:
      - ./target/debug/mvcm
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  test:
    cmds:
      - cargo clippy
      - cargo test

  build:
    cmds:
      - cargo build

  release:
    cmds:
      - cargo build --release

  clean:
    cmds:
      - rm -rf ./target
