---
version: "3"

vars:
  PROJECT_DIR:
    sh: git rev-parse --show-toplevel

env:
  ROOT_DIR: "{{.PROJECT_DIR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  init:
    desc: Install dependencies
    cmds:
      - task: dependencies

  dependencies:
    internal: true
    desc: Project dependencies
    cmds:
        - cargo install cargo-watch
    status:
      - test -f $HOME/.cargo/bin/cargo-watch

  start:
    desc: Compile, run and watch for changes
    aliases:
      - watch
    cmds:
      - cargo watch -x run
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  debug:
    cmds:
      - ./target/debug/mvcm
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: trace

  lint:
    cmds:
      - cargo clippy --locked --release -- -D warnings
      - cargo fmt -- --check

  test:
    cmds:
      - cargo test

  build:
    cmds:
      - task: build-dependencies
      - task: build-target
        vars:
          TARGET: aarch64-apple-darwin

  bundle-dependencies:
    internal: true
    desc: Bundle dependencies
    cmds:
      - cargo install cargo-bundle
    status:
      - test -f $HOME/.cargo/bin/cargo-bundle

  build-target:
    cmds:
      - cargo build --locked --release --target {{ .TARGET }}
      - cargo bundle --release --target {{ .TARGET }}
      - open ./target/{{ .TARGET }}/release/bundle/osx

  release:
    cmds:
      - task: release-dependencies
      - cargo clean
      - task: release-target
        vars:
          TARGET: aarch64-apple-darwin
    env:
      RUST_LOG: warn

  release-dependencies:
    internal: true
    desc: Release dependencies
    cmds:
      - cargo install apple-codesign
      - cargo install toml-cli
    status:
      - test -f $HOME/.cargo/bin/apple-codesign
      - test -f $HOME/.cargo/bin/toml-cli

  release-target:
    internal: true
    cmds:
      - cargo build --locked --release --target {{ .TARGET }}
      - cargo bundle --release --target {{ .TARGET }}
      - rcodesign sign --pem-source {{ .PEM_FILE }} ./target/{{ .TARGET }}/release/bundle/osx/Mic\ Mute.app
      - hdiutil create -volname {{ .TITLE }} -srcfolder ./target/{{ .TARGET }}/release/bundle/osx -ov -format UDZO {{ .TITLE }}.dmg
      # - rcodesign sign --pem-source {{ .PEM_FILE }} {{ .TITLE }}.dmg
    env:
      RUST_LOG: warn
    vars:
      PEM_FILE: sign.crt
      NAME:
        sh: toml get Cargo.toml package.name --raw
      VERSION:
        sh: toml get Cargo.toml package.version --raw
      TITLE: "{{ .NAME }}-{{ .VERSION }}-{{ .TARGET }}"

  clean:
    cmds:
      - cargo clean
