name: Release

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  release:
    name: Release Darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-apple-darwin
          ARCHIVE_TYPES: zip
